export const CommonConstant = {
    DEFAULTERR : "sorry unable to process! please try again later",
    NOTIFICATIONSUCCESS : "NOTIFICATION_SUCCESS",
    NOTIFICATIONCLEAR : "NOTIFICATION_CLEAR",
    GETSTORELISTSUCCESS : "GET_STORE_LIST_SUCCESS",
    GETSTORELISTFAIL : "GET_STORE_LIST_FAIL",
    ADDEDITSTORESUCCESS : "ADD_EDIT_STORE_SUCCESS",
    ADDEDITSTOREFAIL : "ADD_EDIT_STORE_FAIL",
    GETSTOREDETAILBYIDSUCCESS : "GET_STORE_DETAIL_BY_ID_SUCCESS",
    GETSTOREDETAILBYIDFAIL : "GET_STORE_DETAIL_BY_ID_FAIL",
};